declare global {
  type TShirtSize = 'S' | 'M' | 'L' | 'XL'
  type PopoverPlacement =
    | 'top'
    | 'bottom'
    | 'left'
    | 'right'
    | 'top left'
    | 'top right'
    | 'top start'
    | 'top end'
    | 'bottom left'
    | 'bottom right'
    | 'bottom start'
    | 'bottom end'
    | 'left top'
    | 'left bottom'
    | 'right top'
    | 'right bottom'
}
